{
 "title": "Switches",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Port Statistics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(prosafe_receive_bytes_total{}[$__rate_interval])*8",
     "legendFormat": "{{hostname}} Port {{port}} RX"
    },
    {
     "expr": "rate(prosafe_transmit_bytes_total{}[$__rate_interval])*-8",
     "legendFormat": "{{hostname}} Port {{port}} TX"
    }
   ]
  },
  {
   "title": "Port Status",
   "type": "table",
   "gridPos": { "h": 25, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "prosafe_link_speed" },
    { "expr": "prosafe_max_mtu" },
    { "expr": "prosafe_receive_bytes_total" },
    { "expr": "prosafe_transmit_bytes_total" },
    { "expr": "prosafe_error_packets_total" }
   ]
  },
  {
   "title": "Switches",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "prosafe_switch_info" }
   ]
  }
 ]
}